---
- hosts: master
  remote_user: root
  tasks:
    - name: init kubeadm
      command: kubeadm init --apiserver-advertise-address {{ansible_ssh_host}} --pod-network-cidr=10.244.0.0/16 --service-cidr 10.96.0.0/12
    - name: init flannel
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
    - name: init dashboard
      command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
    - name: configure kubectl
      shell: |
        mkdir $HOME/.kube/
        cp -f /etc/kubernetes/admin.conf $HOME/.kube/config

